### ISSUE TITLE
目前最新的版本似乎加密已经改变

### ISSUE THREAD

**Issue by zhanglei-55** [Rockytkg/AutoMoGuDingCheckIn#10]

**Comment by zhanglei-55** [comment]
![image](https://github.com/user-attachments/assets/507dfc10-7068-448c-a5b1-5d0126de3a8c)

**Comment by Rockytkg** [comment]
v5版本的接口还能正常使用，最新的v6接口前几天就已经支持了，重新拉项目安装依赖填写配置即可

**Comment by zhanglei-55** [comment]
> v5版本的接口还能正常使用，最新的v6接口前几天就已经支持了，重新拉项目安装依赖填写配置即可

好的感谢
