### ISSUE TITLE
提交周报异常

### ISSUE THREAD

**Issue by Alanosy** [Rockytkg/AutoMoGuDingCheckIn#20]
问题1:调用函数get_job_info时返回值为 {'code': 200, 'msg': 'success', 'data': None}
在后面使用get函数获取获取数据时报错'NoneType' object has no attribute 'get'

问题2:这个job id在提交周报时是必要的吗，能否去掉？

**Comment by Alanosy** [comment]
添加以下代码已解决
rsp = self._post_request(url, headers, data, '获取岗位信息失败')
        result = rsp.get('data', {})
        if result==None:
            result = {"jobId":""}
        return result

**Comment by Rockytkg** [comment]
jobid字段是app提交的时候有的，你删掉不要是否后台会显示异常？这个字段正常来说，提交实习申请之后就会有的，根据工学云的实习流程是 提交实习申请（岗位信息，上传相关的信息） -> 正式开始实习，如果不要这个字段，后面会不会导致异常？

**Comment by Alanosy** [comment]
> jobid字段是app提交的时候有的，你删掉不要是否后台会显示异常？这个字段正常来说，提交实习申请之后就会有的，根据工学云的实习流程是 提交实习申请（岗位信息，上传相关的信息） -> 正式开始实习，如果不要这个字段，后面会不会导致异常？

我在app上看了是提交成功的

**Comment by Rockytkg** [comment]
提交是会成功，可是你没有jobid是因为没有提交相应的实习申请，单纯打完卡也能算完成实习？

**Comment by Rockytkg** [comment]
还有就是注意到你的提交中含有pyc文件，pyc文件不应该包含在提交中

**Comment by Rockytkg** [comment]
还有关于定时任务部分，linux系统有自带的定时任务程序cron，直接使用系统定时任务感觉比在代码中实现定时器更好

**Comment by Alanosy** [comment]
> 还有关于定时任务部分，linux系统有自带的定时任务程序cron，直接使用系统定时任务感觉比在代码中实现定时器更好

那推荐出一个shell脚本来执行定时

**Comment by Alanosy** [comment]
> 提交是会成功，可是你没有jobid是因为没有提交相应的实习申请，单纯打完卡也能算完成实习？

确实没有实习申请，属于特殊情况吧，不过请求接口确实是none
