### ISSUE TITLE
上午打卡的问题

### ISSUE THREAD

**Issue by houyunlong1668** [Rockytkg/AutoMoGuDingCheckIn#23]
为啥基本都是上午10点多打上卡

**Comment by Rockytkg** [comment]
请问是采用的那种方式部署嘞，如果是github工作流的话这个是正常的，本身就会有偏移，这个是无法避免的，你可以改为非高峰期打卡

**Comment by houyunlong1668** [comment]
> 请问是采用的那种方式部署嘞，如果是github工作流的话这个是正常的，本身就会有偏移，这个是无法避免的，你可以改为非高峰期打卡

是github的工作流。明白哈，谢谢
