### ISSUE TITLE
服务器定时打卡

### ISSUE THREAD

**Issue by 1916757740** [Rockytkg/AutoMoGuDingCheckIn#24]
就是在服务器设置定时打卡之后，该怎么改变定时时间

**Comment by Rockytkg** [comment]
执行`crontab -e`然后修改

**Comment by 1916757740** [comment]
什么时候增加写总结文章的功能 @Rockytkg

**Comment by Rockytkg** [comment]
总结的话，好像大部分都是一千字以上，AI直接写有点写不出来😂

**Comment by Rockytkg** [comment]
可是总结基本上都是2000起，而且总结只需要写一次，所以我觉得没多大必要，还浪费模型token，以及优化提示词，不如自己写

**Comment by successno** [comment]
大佬为什么我的会出现***9：41*** __main__错误：打卡失败：“ConfigManager”对象没有属性“clockIn”这个问题

**Comment by Rockytkg** [comment]
> 大佬为什么我的会出现_**9：41**_ __main__错误：打卡失败：“ConfigManager”对象没有属性“clockIn”这个问题

同步最新代码
