### ISSUE TITLE
对于配置文件说明的疑惑&对人工智能语言模型配置的疑惑

### ISSUE THREAD

**Issue by DTY77** [Rockytkg/AutoMoGuDingCheckIn#26]
### 我不是学it相关专业的，本人纯小白，望见谅。如有冒犯这里先道歉：对不起。

1. 对于：“周记提交时间（以小时为单位，范围为0-23）”在配置说明文件和项目说明文件中的解释表示疑惑。在配置时，我将其值设置为22。原以为他将在周一至周日的其中一天的22时，为我提交周报。但它并未发生。任务报告中一直为：未到周报提交时间。自然也并未帮我提交周报。
2. 目前已将其值更改为：1  等待变化中ing…
3. 对于jason文件语言模型配置的疑惑：不知其是否配置正确；不能配置发出的话语(没有该选项)。

### 以上问题的环境说明：
观测该问题时段为12月9日至12月15日； 
问题时段中的周报一段json配置为：
weekly": {
        "enabled": true,
        "imageCount": 0,
        "submitTime": 22
；
语言模型配置为阿里云百炼语言模型：通义千问max，官方文档说对Open AI chat接口兼容。
json文本配置为：
    "ai": {
      "model": "qwen-max",
      "apikey": "sk-马赛克马赛克马赛克马赛克马赛克",
      "apiUrl": "https://dashscope.aliyuncs.com/compatible-mode/v1"

**Comment by Rockytkg** [comment]
文档说明有误，这里应该填写周几，例如写4就是在周四提交周报

**Comment by Rockytkg** [comment]
你的链接也填写错误了apiUrl应该配置为 "https://dashscope.aliyuncs.com/compatible-mode"，不需要后面的/v1

**Comment by DTY77** [comment]
谢谢你，但我非常想知道该环境下为什么反斜杠后不应存在v1

**Comment by Rockytkg** [comment]
/v1/chat/completions被硬编码在代码中
