### ISSUE TITLE
关于周保中的必答问题：问卷内容

### ISSUE THREAD

**Issue by DTY77** [Rockytkg/AutoMoGuDingCheckIn#27]
首先，对项目作者的无私奉献表达感谢！

今天突然发现提交周报时，必须填写问卷内容，否则无法提交。提示问卷内容为必选项，目前，问卷为单选题，猜测未来可能会加入多选题，且规定选项不少于两个。猜测未来可能加入简答题，并设置字数要求。

再次恳请大佬出山对此作出应对。抱拳(手动emoji)
![IMG_20241218_013233](https://github.com/user-attachments/assets/8f2723f6-bedc-468b-bb03-8944732a6467)

**Comment by Rockytkg** [comment]
可以提供更多信息嘛，例如周报提交失败相日志确定问卷必填，以及能否提供账号，因为我提交周报目前一切正常，没有要求填写问卷

**Comment by youngwomen123** [comment]
我们的周报也会有选择题这样的内容

**Comment by Rockytkg** [comment]
目前没有有这个问题的账号，我需要通过提交一次周报，抓包得到参数和逻辑

**Comment by Rockytkg** [comment]
> 我们的周报也会有选择题这样的内容

如果要解决这个问题需要有人愿意提供一个需要填写问卷的账号才行

> 目前没有有这个问题的账号，我需要通过提交一次周报，抓包得到参数和逻辑

**Comment by youngwomen123** [comment]
好的等大佬的好消息




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月29日(星期天) 下午4:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Rockytkg/AutoMoGuDingCheckIn] 关于周保中的必答问题：问卷内容 (Issue #27)














 
目前没有有这个问题的账号，我需要通过提交一次周报，抓包得到参数和逻辑

**Comment by Rockytkg** [comment]
已经更新了，同步最新代码测试

**Comment by DTY77** [comment]
辛苦了，提前祝你：新年快乐🙏












2628993464
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月30日(周一) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Rockytkg/AutoMoGuDingCheckIn] 关于周保中的必答问题：问卷内容 (Issue #27)




 
已经更新了，同步最新代码测试
