### ISSUE TITLE
大佬为什么我的会显示无打卡属性

### ISSUE THREAD

**Issue by successno** [Rockytkg/AutoMoGuDingCheckIn#29]
<img width="422" alt="1734574556507" src="https://github.com/user-attachments/assets/afc6e8e5-6aee-45c9-8adb-e313de370a1e" />

**Comment by Rockytkg** [comment]
同步最新代码

**Comment by successno** [comment]
最新代码在哪查看

**Comment by Rockytkg** [comment]
现在仓库就是啊

**Comment by successno** [comment]
好的我去主页更新谢谢
