### ISSUE TITLE
打卡失败：考勤失败

### ISSUE THREAD

**Issue by fengwen987654** [Rockytkg/AutoMoGuDingCheckIn#31]
您好，感谢您的无私奉献，今天使用的时候发生了以下状况
![QQ20241220-160532](https://github.com/user-attachments/assets/75e4d02e-2529-4579-bbba-56f2a7cadc89)
更新代码后依然无法打卡，能麻烦您看一下吗

**Comment by successno** [comment]
缺少打卡模式类型 代码缺失了

**Comment by Rockytkg** [comment]
> 缺少打卡模式类型 代码缺失了

能说详细点吗

**Comment by successno** [comment]
> > 缺少打卡模式类型 代码缺失了
> 
> 能说详细点吗

是他的代码填的时候应该是失误删掉了

**Comment by Rensr0** [comment]
> > > 缺少打卡模式类型 代码缺失了
> > 
> > 
> > 能说详细点吗
> > ai那里需要自己去注册一个吗 周报的ai我用不了

ai需要自己申请api正确填入后才可以使用，否则无法进行日报和周报以及月报。

**Comment by fengwen987654** [comment]
> > 缺少打卡模式类型 代码缺失了
> 
> 能说详细点吗

您好，我更新过最新的代码，刚刚又重新检查一遍确认没有缺少代码

**Comment by Rockytkg** [comment]
> > > 缺少打卡模式类型 代码缺失了
> > 
> > 
> > 能说详细点吗
> > ai那里需要自己去注册一个吗 周报的ai我用不了

ai功能可以推荐使用阿里百炼 目前免费 或者deepseek 1块钱够一个人实习的全部了 兼容openai格式的接口均可以，考勤失败应该是gxy更新了，目前应该是在灰度状态

**Comment by successno** [comment]
> > > 缺少打卡模式类型 代码缺失了
> > 
> > 
> > 能说详细点吗
> 
> 您好，我更新过最新的代码，刚刚又重新检查一遍确认没有缺少代码

那你现在能用吗

**Comment by shisanjin123** [comment]
现在还是不能用，是继续等待吗

**Comment by Rockytkg** [comment]
有愿意提供账号测试的吗，需要打一次卡抓包参数

**Comment by shisanjin123** [comment]
如何提供呢

**Comment by Rockytkg** [comment]
发送邮件到liushicoto@foxmail.com

**Comment by successno** [comment]
> 有愿意提供账号测试的吗，需要打一次卡抓包参数

我都能用
我今天还测试了5次
都可以

**Comment by fengwen987654** [comment]
> > > > 缺少打卡模式类型 代码缺失了
> > > 
> > > 
> > > 能说详细点吗
> > 
> > 
> > 您好，我更新过最新的代码，刚刚又重新检查一遍确认没有缺少代码
> 
> 那你现在能用吗

用不了，依然是上面的情况

**Comment by Rockytkg** [comment]
> > 有愿意提供账号测试的吗，需要打一次卡抓包参数
> 
> 我都能用 我今天还测试了5次 都可以

因为目前处于灰度阶段，就像上次登陆接口一样

**Comment by Rockytkg** [comment]
这几天应该就会逐步失效

**Comment by fengwen987654** [comment]
> 发送邮件到 [liushicoto@foxmail.com](mailto:liushicoto@foxmail.com)

您好，还有一个新的问题，我是多用户打卡，到昨天为止我的卡都能正常打卡推送，但我的朋友推送显示正常，实际却只有一天打卡了，检查运行流程没有问题，照常运行

**Comment by Rockytkg** [comment]
> > 发送邮件到 [liushicoto@foxmail.com](mailto:liushicoto@foxmail.com)
> 
> 您好，还有一个新的问题，我是多用户打卡，到昨天为止我的卡都能正常打卡推送，但我的朋友推送显示正常，实际却只有一天打卡了，检查运行流程没有问题，照常运行

刷新app，清除数据重新进，app不会每次从服务器更新数据的，建议从实习进度界面查看是否打上卡

**Comment by Rockytkg** [comment]
> > 发送邮件到 [liushicoto@foxmail.com](mailto:liushicoto@foxmail.com)
> 
> 您好，还有一个新的问题，我是多用户打卡，到昨天为止我的卡都能正常打卡推送，但我的朋友推送显示正常，实际却只有一天打卡了，检查运行流程没有问题，照常运行

已经更新，可以去测试以下吗

**Comment by hhd6624** [comment]
还是一样的

**Comment by successno** [comment]
> 还是一样的

你们用手机还是电脑

**Comment by fengwen987654** [comment]
> > > 发送邮件到 [liushicoto@foxmail.com](mailto:liushicoto@foxmail.com)
> > 
> > 
> > 您好，还有一个新的问题，我是多用户打卡，到昨天为止我的卡都能正常打卡推送，但我的朋友推送显示正常，实际却只有一天打卡了，检查运行流程没有问题，照常运行
> 
> 已经更新，可以去测试以下吗

您好，用更新的代码试了好几次，打卡类型显示end，运行显示打卡成功且有推送但在gxy上显示未打卡，用您上面说的清缓存重装也不行

**Comment by Rockytkg** [comment]
等会儿我回去了再看看吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月20日(周五) 晚上8:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Rockytkg/AutoMoGuDingCheckIn] 打卡失败：考勤失败 (Issue #31)




    
发送邮件到 ***@***.***
  
您好，还有一个新的问题，我是多用户打卡，到昨天为止我的卡都能正常打卡推送，但我的朋友推送显示正常，实际却只有一天打卡了，检查运行流程没有问题，照常运行
  
已经更新，可以去测试以下吗
  
您好，用更新的代码试了好几次，打卡类型显示end，运行显示打卡成功且有推送但在gxy上显示未打卡，用您上面说的清缓存重装也不行

**Comment by fengwen987654** [comment]
> 等会儿我回去了再看看吧
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月20日(周五) 晚上8:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [Rockytkg/AutoMoGuDingCheckIn] 打卡失败：考勤失败 (Issue #31) 发送邮件到 ***@***.*** 您好，还有一个新的问题，我是多用户打卡，到昨天为止我的卡都能正常打卡推送，但我的朋友推送显示正常，实际却只有一天打卡了，检查运行流程没有问题，照常运行 已经更新，可以去测试以下吗 您好，用更新的代码试了好几次，打卡类型显示end，运行显示打卡成功且有推送但在gxy上显示未打卡，用您上面说的清缓存重装也不行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

麻烦您了谢谢

**Comment by fengwen987654** [comment]
> 等会儿我回去了再看看吧
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月20日(周五) 晚上8:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [Rockytkg/AutoMoGuDingCheckIn] 打卡失败：考勤失败 (Issue #31) 发送邮件到 ***@***.*** 您好，还有一个新的问题，我是多用户打卡，到昨天为止我的卡都能正常打卡推送，但我的朋友推送显示正常，实际却只有一天打卡了，检查运行流程没有问题，照常运行 已经更新，可以去测试以下吗 您好，用更新的代码试了好几次，打卡类型显示end，运行显示打卡成功且有推送但在gxy上显示未打卡，用您上面说的清缓存重装也不行 — 您好，今天运行的时候打卡地点变成了您的默认设置，但我的代码全部改过地址的，我已经删除了代码库，等零点重新复制运行一次

**Comment by fengwen987654** [comment]
您好，今天显示打卡类型start，但依然是打卡失败，考勤失败

**Comment by hhd6624** [comment]
> 您好，今天显示打卡类型开始，但仍然是打卡失败，考勤失败

我也是

**Comment by Rockytkg** [comment]
这两天有些忙，等明天有空了看吧，还有就是我手上十几个人都能正常打卡，看讨论中也有人是正常打卡的，你们可以检查一下定位的经纬度是不是和你们实习计划上提交的经纬度偏差太大了导致的

**Comment by fengwen987654** [comment]
白天程序自动签到打卡推送运行正常，但工学云显示不了，重复签到也不会显示卡已打

**Comment by houyunlong1668** [comment]
> 白天程序自动签到打卡推送运行正常，但工学云显示不了，重复签到也不会显示卡已打

老铁，我今天的卡打上了（只开了一个打卡功能，周报什么的没开），是不是配置文件的问题

**Comment by fengwen987654** [comment]
> > 白天程序自动签到打卡推送运行正常，但工学云显示不了，重复签到也不会显示卡已打
> 
> 老铁，我今天的卡打上了（只开了一个打卡功能，周报什么的没开），是不是配置文件的问题

我也只开了一个打卡功能，也试了几次还是运行成功推送显示完成但gxy不显示

**Comment by HopeHak** [comment]
> 这两天有些忙，等明天有空了看吧，还有就是我手上十几个人都能正常打卡，看讨论中也有人是正常打卡的，你们可以检查一下定位的经纬度是不是和你们实习计划上提交的经纬度偏差太大了导致的

大佬，我也所有功能正常呢，我部署GitHub试了因为怕有IP的检测所以还是放到服务器上去运行了。目前一切正常！

**Comment by hhd6624** [comment]
默认地址可以打卡，自己改地址就打卡打卡失败：考勤失败

**Comment by houyunlong1668** [comment]
> 默认地址可以打卡，自己改地址就打卡打卡失败：考勤失败

地址上的每一个点前后都有空格，还有经纬度要改，应该能用的，检查一下，我的问题是pushplus有时候不推送，今天是四次推送都推了，应该没问题。

**Comment by Rockytkg** [comment]
> > 默认地址可以打卡，自己改地址就打卡打卡失败：考勤失败
> 
> 地址上的每一个点前后都有空格，还有经纬度要改，应该能用的，检查一下，我的问题是pushplus有时候不推送，今天是四次推送都推了，应该没问题。

所有的人都可以尝试一这个方式，接口那些参数都没有更新，请求方式也没有变更

**Comment by fengwen987654** [comment]
> > > 默认地址可以打卡，自己改地址就打卡打卡失败：考勤失败
> > 
> > 
> > 地址上的每一个点前后都有空格，还有经纬度要改，应该能用的，检查一下，我的问题是pushplus有时候不推送，今天是四次推送都推了，应该没问题。
> 
> 所有的人都可以尝试一这个方式，接口那些参数都没有更新，请求方式也没有变更

您好，刚刚已经改过一遍了，打卡依然是失败，可能是电脑的问题吗

**Comment by Rockytkg** [comment]
能提供下配置文件吗，发送到邮箱liushicoto@foxmail.com

**Comment by Rockytkg** [comment]
这个bug确实是可能部分人有，确保打卡地点那些格式和官方一致

**Comment by Rensr0** [comment]
> 白天程序自动签到打卡推送运行正常，但工学云显示不了，重复签到也不会显示卡已打

如果使用程序打卡之后，想要在手机app中查看打卡记录是要退出账号重新登陆才会正常显示的。

**Comment by Rockytkg** [comment]
> > > > 默认地址可以打卡，自己改地址就打卡打卡失败：考勤失败
> > > 
> > > 
> > > 地址上的每一个点前后都有空格，还有经纬度要改，应该能用的，检查一下，我的问题是pushplus有时候不推送，今天是四次推送都推了，应该没问题。
> > 
> > 
> > 所有的人都可以尝试一这个方式，接口那些参数都没有更新，请求方式也没有变更
> 
> 您好，刚刚已经改过一遍了，打卡依然是失败，可能是电脑的问题吗

调查出结果了，注意经纬度不要填写错误了，检查发现你的经纬度填写错误了，错误的将经度填写到纬度变量了，纬度填写到经度变量了

**Comment by Rockytkg** [comment]
> 默认地址可以打卡，自己改地址就打卡打卡失败：考勤失败

经纬度填写错误，请检查

**Comment by Rockytkg** [comment]
> 现在还是不能用，是继续等待吗

检查配置文件经纬度是否填写反了"latitude"表示纬度，"longitude"表示经度

**Comment by Rockytkg** [comment]
测试好了请反馈一下

**Comment by hhd6624** [comment]
> > 现在还是不能用，是继续等待吗
> 
> 检查配置文件经纬度是否填写反了"latitude"表示纬度，"longitude"表示经度

确定填反了，习惯了经纬，都没注意到
