### ISSUE TITLE
运行后  消息推送发现打卡失败

### ISSUE THREAD

**Issue by AlmostOvO** [Rockytkg/AutoMoGuDingCheckIn#33]
![Uploading 微信图片_20241221151725.png…]()

**Comment by Rockytkg** [comment]
看日志是你的账号或者密码错误了

**Comment by AlmostOvO** [comment]
> 看日志是你的账号或者密码错误了

我使用ai 修改了一下后可以运行了谢谢

**Comment by AlmostOvO** [comment]
现在出现了一个新的问题  就是我账号跟密码都是正确的因为我能直接登陆软件  但是运行后显示获取API客户端失败:登陆失败，账号不存在或密码错误!
并且显示ERROR:打卡失败:type object 'datetime.datetime" has no attribute 'datetime'

**Comment by Rockytkg** [comment]
报错 ERROR:打卡失败:type object 'datetime.datetime" has no attribute 'datetime' 应该是ai给你改错了一处代码实际登陆已经成功能，你可能是用的工作流，但是没有删除user目录下的示例配置文件，所以会有个报错登陆失败，账号不存在或密码错误!

**Comment by AlmostOvO** [comment]
> 报错 ERROR:打卡失败:type object 'datetime.datetime" has no attribute 'datetime' 应该是ai给你改错了一处代码实际登陆已经成功能，你可能是用的工作流，但是没有删除user目录下的示例配置文件，所以会有个报错登陆失败，账号不存在或密码错误!

![微信图片_20241221172431](https://github.com/user-attachments/assets/06ae3714-54c5-4b8d-b4cc-6236431bce00)
那我现在是需要这么去修改他

**Comment by Rockytkg** [comment]
建议删除仓库重新fork，仓库代码本身没有问题

**Comment by AlmostOvO** [comment]
> 建议删除仓库重新fork，仓库代码本身没有问题

大佬 我重新把仓库fork了一遍  JSON 配置文件也是按照您给出的建议修改的  它还是这样怎么办
![微信图片_20241221174140](https://github.com/user-attachments/assets/6fc0f3ff-82c3-4bc4-b86a-909ba406cce3)

**Comment by Rockytkg** [comment]
可是代码没有这个问题哇，能提供下你的配置文件吗，注意删除敏感信息喔

**Comment by Rockytkg** [comment]
已修复

**Comment by AlmostOvO** [comment]
> 可是代码没有这个问题哇，能提供下你的配置文件吗，注意删除敏感信息喔

{
  "config": {
    "user": {
      "phone": "",
      "password": ""
    },
    "clockIn": {
      "mode": "custom",
      "location": {
        "address": "湖南省 · 永州市 · 蓝山县 · 塔峰镇下城村附近",
        "latitude": "25.413623",
        "longitude": "112.184922",
        "province": "湖南省",
        "city": "永州市",
        "area": "蓝山县"
      },
      "imageCount": 0,
      "description": [],
      "specialClockIn": "custom",
      "customDays": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    "reportSettings": {
      "daily": {
        "enabled": false,
        "imageCount": 0
      },
      "weekly": {
        "enabled": false,
        "imageCount": 0,
        "submitTime": 4
      },
      "monthly": {
        "enabled": false,
        "imageCount": 0,
        "submitTime": 29
      }
    },
    "ai": {
      "model": "gpt-4o-mini",
      "apikey": "sk-osdhgosdipghpsdgjiosfvinoips",
      "apiUrl": "https://api.openai.com/"
    },
    "pushNotifications": [
      {
        "type": "Server",
        "enabled": true,
        "sendKey": "SCT265260TXVDVG3E5sgE7FXKP7xXVE77L"
      },
      {
        "type": "PushPlus",
        "enabled": true,
        "token": "7b71a4b9b11342868092a1cf09a999f3"
      },
      {
        "type": "AnPush",
        "enabled": false,
        "token": "your_token",
        "channel": "通道ID,多个用英文逗号隔开",
        "to": "根据官方文档获取"
      },
      {
        "type": "WxPusher",
        "enabled": false,
        "spt": "your_spt"
      },
      {
        "type": "SMTP",
        "enabled": false,
        "host": "smtp服务地址",
        "port": 465,
        "username": "发件人邮箱",
        "password": "smtp密码",
        "from": "发件人名称",
        "to": "收件人邮箱"
      }
    ],
    "device": "{brand: vivo V2080A, systemVersion: 11, Platform: Android, isPhysicalDevice: true, incremental: eng.compil.20240715.151140}"
  }
}

**Comment by Rockytkg** [comment]
> > 可是代码没有这个问题哇，能提供下你的配置文件吗，注意删除敏感信息喔
> 
> { "config": { "user": { "phone": "", "password": "" }, "clockIn": { "mode": "custom", "location": { "address": "湖南省 · 永州市 · 蓝山县 · 塔峰镇下城村附近", "latitude": "25.413623", "longitude": "112.184922", "province": "湖南省", "city": "永州市", "area": "蓝山县" }, "imageCount": 0, "description": [], "specialClockIn": "custom", "customDays": [ 1, 2, 3, 4, 5 ] }, "reportSettings": { "daily": { "enabled": false, "imageCount": 0 }, "weekly": { "enabled": false, "imageCount": 0, "submitTime": 4 }, "monthly": { "enabled": false, "imageCount": 0, "submitTime": 29 } }, "ai": { "model": "gpt-4o-mini", "apikey": "sk-osdhgosdipghpsdgjiosfvinoips", "apiUrl": "https://api.openai.com/" }, "pushNotifications": [ { "type": "Server", "enabled": true, "sendKey": "SCT265260TXVDVG3E5sgE7FXKP7xXVE77L" }, { "type": "PushPlus", "enabled": true, "token": "7b71a4b9b11342868092a1cf09a999f3" }, { "type": "AnPush", "enabled": false, "token": "your_token", "channel": "通道ID,多个用英文逗号隔开", "to": "根据官方文档获取" }, { "type": "WxPusher", "enabled": false, "spt": "your_spt" }, { "type": "SMTP", "enabled": false, "host": "smtp服务地址", "port": 465, "username": "发件人邮箱", "password": "smtp密码", "from": "发件人名称", "to": "收件人邮箱" } ], "device": "{brand: vivo V2080A, systemVersion: 11, Platform: Android, isPhysicalDevice: true, incremental: eng.compil.20240715.151140}" } }

已经修复，同步最新代码库测试
