### ISSUE TITLE
关于修改信息问题

### ISSUE THREAD

**Issue by ebcbbt** [Rockytkg/AutoMoGuDingCheckIn#38]
我不需要日报什么的只需要打卡修改我的账号信息和打卡地址去运行就好了是吧，可以手动点击什么时候打卡吗还是只能预定时间，有什么方法检验运行成功

**Comment by ebcbbt** [comment]
JSON,是只要复制自己修改过的数据还是全部都要复制过去

**Comment by Rockytkg** [comment]
Q1：需要修改账号信息、打卡地点、经纬度、打卡模式（默认每天打上下班卡）
Q2：可以手动运行
Q3：配置推送或者每天自行登陆工学云查看运行结果
Q4：全部

**Comment by ebcbbt** [comment]
不知道哪里有问题我设置下午3点打卡但是工学云并没有显示打卡成功的记录

**Comment by Rockytkg** [comment]
请提供运行日志

**Comment by ebcbbt** [comment]
![屏幕截图 2024-12-24 151446](https://github.com/user-attachments/assets/2b6df9cf-7f80-4a2d-b54d-dec825b39d87)
是这个吗

**Comment by Rockytkg** [comment]
你的配置文件有误
![image](https://github.com/user-attachments/assets/684ff19f-0309-4204-b515-d04f835b196d)

**Comment by ebcbbt** [comment]
![屏幕截图 2024-12-24 154048](https://github.com/user-attachments/assets/9b6934e5-7ed0-4ada-9d6c-85fd61152838)
我重新按操作了一次，这是哪里有问题需要改，哥你帮我看看

**Comment by Rockytkg** [comment]
同步最新代码后运行试试

**Comment by Rockytkg** [comment]
删除仓库重新 fork 就好了

**Comment by ebcbbt** [comment]
![屏幕截图 2024-12-24 161659](https://github.com/user-attachments/assets/3737f649-cb26-40c3-9e48-20cdaee2c7b6)
删除库重新fork问题解决了，但是账号和密码还是显示错误我可以私发给你看看我改的JSON，您帮我看看哪里有问题可以吗

**Comment by Rockytkg** [comment]
发送到liushicoto@foxmail.com

**Comment by ebcbbt** [comment]
哥有没有视频教程，我对这个不了解搞了6小时了还是搞不是很明白运行环境这些不会弄，还是说我直接放弃

**Comment by successno** [comment]
用python
运行

**Comment by Rockytkg** [comment]
> 哥有没有视频教程，我对这个不了解搞了6小时了还是搞不是很明白运行环境这些不会弄，还是说我直接放弃

你是要用GitHub部署？我可以帮你部署，发送联系方式到我邮箱

**Comment by ebcbbt** [comment]
谢谢哥，使用 github 是因为我在百度搜索到的教程刚好是这个，我就优先使用这个，但是失败了，我的基础不好，python 后续我会去尝试，现在我有方便的方法去异地打卡工学云，但是我也会接着去学习有关知识，尝试用代码脚本的方式，后续 python 失败了在联系大佬你
