### ISSUE TITLE
关于ai的配置问题

### ISSUE THREAD

**Issue by P4rfa1t** [Rockytkg/AutoMoGuDingCheckIn#42]
![微信截图_20241226153616](https://github.com/user-attachments/assets/60a0594c-e812-4ef0-8a1e-fda707bd3f5f)
如图，用的openai的api，一直都是429，用其他国产的api，并不是很清楚如何配置

**Comment by Rockytkg** [comment]
兼容openai格式的都可以，填写对应的api地址模型名还有key就好了
