### ISSUE TITLE
日报周报月报不能正常获取并提交

### ISSUE THREAD

**Issue by bvjhgsfdbcsd** [Rockytkg/AutoMoGuDingCheckIn#48]
显示NoneType' object has no attribute 'get，并且周报，月报更新有必填的问卷调查，求求更新

**Comment by Rockytkg** [comment]
关于报错，请检查 ai 配置是否正确，关于必填问卷，请移步 #27 讨论，目前没人愿意提供一个账号给我，我需要提交一次周报抓包才行，直接逆向太困难了

**Comment by bvjhgsfdbcsd** [comment]
ai配置没问题，我重写测试过确实能生成，开启就报错，目前我这个月的我的提交过了，要等下个月了

![23040f565812c7ef7325484e6072362](https://github.com/user-attachments/assets/8723e00e-8584-41cd-a01c-a00e85d42bbd)
