### ISSUE TITLE
打卡时多了一个附件

### ISSUE THREAD

**Issue by Rensr0** [Rockytkg/AutoMoGuDingCheckIn#6]
#### 描述
在打卡功能中，发现每次打卡时都会多出一个不必要的附件。具体情况如下：

- 附件链接：![附件](https://github.com/user-attachments/assets/f9c7fada-6fdb-43c7-99bb-e94380c89fc4)
  
#### 重现步骤
通过服务器部署后进行打卡后发现打卡历史出现了一个附件，点进去会是一个错误的json信息。

#### 期望行为
希望在打卡时不再出现多余附件。

#### 附加信息
- 设备信息：Ubuntu。

期待尽快解决这个问题！

**Comment by Rensr0** [comment]
"clockInImageCount": 0,

这个位置填写的是0

**Comment by Rockytkg** [comment]
修了修了
