### ISSUE TITLE
{'code': 500, 'msg': '请到应用宝或者工学云网站下载最新版本APP'}

### ISSUE THREAD

**Issue by xioamingzxm** [Rockytkg/AutoMoGuDingCheckIn#7]
{'code': 500, 'msg': '请到应用宝或者工学云网站下载最新版本APP'}
我通过抓包发现登录时的data中的：captcha不再为none，uuid也不为空
        "phone": account_,
        "password": password_,
        "loginType": "android",
        "uuid": "",
        "captcha":None,
        "t": getT(),
        "version":"5.14.0"

**Comment by Rockytkg** [comment]
不会修复建议直接抓包拿到token等

**Comment by Rockytkg** [comment]
uuid是随机生成的，验证码是滑块验证码，我无能为力，建议登录后抓包获取token等参数填写

**Comment by Rockytkg** [comment]
目前老接口似乎还是能使用的？可能你一个ip挂了太多人了吧，最新版的加上了滑动验证码后续有空可能会尝试解决
![image](https://github.com/user-attachments/assets/d01ebf9b-f189-4d03-a79f-45f2b9dc8c3d)

**Comment by Rockytkg** [comment]
已经兼容最新接口
